# import User from 'user.gql'

scalar DateTime

input SignUpInput {
    firstName: String!
    lastName: String!
    username: String!
    password: String!
}

input SignInInput {
    username: String!
    password: String!
}

type AuthUserPayload {
    successful: Boolean!
}
