# import User from 'user.gql'

scalar DateTime

input SignUpInput {
    firstName: String!
    lastName: String!
    username: String!
    password: String!
}

input SignInInput {
    username: String!
    password: String!
}
type UserPayLoad {
    id: ID!
    username: String!
}
type AuthErrorPayload {
    message: String
    name: String
}
type AuthUserPayload {
    success: Boolean!
    error: AuthErrorPayload
    token: String!
    user: UserPayLoad!
}
