# import User from "user.gql"
# import Message from "messages.gql"

type UserPayload {
  success: Boolean!
  error: ErrorPayload
  user: User
}

type ErrorPayload {
  name: String
  message: String
}

type InboxPayload {
  success: Boolean!
  error: ErrorPayload
  messages: [Message]
}

type OutboxPayload {
  success: Boolean!
  error: ErrorPayload
  messages: [Message]
}

type StarredPayload {
  success: Boolean!
  error: ErrorPayload
  messages: [Message]
}

type DraftsPayload {
  success: Boolean!
  error: ErrorPayload
  messages: [Message]
}
type SpamPayload {
  success: Boolean!
  error: ErrorPayload
  messages: [Message]
}

type TrashPayload {
  success: Boolean!
  error: ErrorPayload
  messages: [Message]
}

type MessagePayload {
  success: Boolean!
  error: ErrorPayload
  message: [Message]
}