# import SignUpInput, SignInInput, AuthUserPayload from "mutations.gql"

type Query {
    username: String!
}

type Mutation {
    signUp(input: SignUpInput!): AuthUserPayload!
    signIn(input: SignInInput!): AuthUserPayload!
}