# import Contact from "contacts.gql"

scalar DateTime

type User {
    id: ID!
    firstName: String!
    lastName: String!
    email: String!
    messagesId: [ID!]!
    username: String!
    contacts: [Contact!]!
    created: DateTime!
}