# import Contact from "contacts.gql"

scalar DateTime

type User {
    id: ID!
    firstName: String!,
    lastName: String!
    email: String!
    username: String!
    contacts: [Contact!]!
    created: DateTime!
}